export const LANDING_PAGE = {
  SET_SEARCH_VALUE: "LANDING_PAGE_SET_SEARCH_VALUE",
  CHARACTERS_API_STARTED: "LANDING_PAGE_CHARACTERS_API_STARTED",
  CHARACTERS_API_LOAD_MORE_STARTED: "LANDING_PAGE_CHARACTERS_API_LOAD_MORE_STARTED",
  CHARACTERS_API_SUCCESS: "LANDING_PAGE_CHARACTERS_API_SUCCESS",
};

export const CHARACTER_PAGE = {
  API_STARTED: "CHARACTER_PAGE_API_STARTED",
  SET_DATA: "CHARACTER_PAGE_SET_DATA",
  CLEAR_DATA: "CHARACTER_PAGE_CLEAR_DATA",
};
